package curlin.danko.bikefitting.export

import curlin.danko.bikefitting.model.dao.BikeFittingDAO
import curlin.danko.bikefitting.model.dto.InputForm
import java.time.Instant
import java.time.LocalDate
import java.util.Locale

data class CsvRowMeta(
    val id: String,
    val fullName: String,
    val fitterFullName: String,
    val sessionInstant: Instant,
    val submissionDate: LocalDate,
    val hasPdf: Boolean,
)

/**
 * Excel-friendly flat CSV: UTF-8 with BOM (written by caller), CRLF, comma-separated,
 * RFC 4180 quoting via Apache Commons CSV EXCEL format.
 */
object BikeFittingCsvSchema {

    private val META_HEADERS = listOf(
        "record_id",
        "record_full_name",
        "record_fitter_full_name",
        "session_instant",
        "submission_date",
        "has_pdf",
    )

    /**
     * Matches [InputForm] field order; nested [InputForm.fitter] is expanded to three columns
     * after `phone`.
     */
    private val FORM_HEADERS = listOf(
        "date",
        "fullName",
        "email",
        "phone",
        "fitterFullName",
        "fitterEmail",
        "fitterPhone",
        "cyclingExperienceLevel",
        "cyclingExperienceYears",
        "cyclingFrequency",
        "cyclingProblem",
        "cyclingConcerns",
        "ischialTuberosity",
        "height",
        "inseam",
        "shoulderWidth",
        "footLengthLeft",
        "footLengthRight",
        "footWidthLeft",
        "footWidthRight",
        "forefootAngulationTypeLeft",
        "forefootAngulationTypeRight",
        "forefootAngulationSeverityLeft",
        "forefootAngulationSeverityRight",
        "rearFootStructureLeft",
        "rearFootStructureRight",
        "neutralArchHeightLeft",
        "neutralArchHeightRight",
        "lowerExtremityAlignmentLeft",
        "lowerExtremityAlignmentRight",
        "advLowerExtremityAlignment",
        "levelPelvis",
        "spinalCurveEvaluation",
        "advScapularPositionType",
        "advScapularPositionSeverity",
        "cervicalSpineROM",
        "shoulderROM",
        "hamstringROMLeft",
        "hamstringROMRight",
        "hipROMLeft",
        "hipROMRight",
        "advPassiveHipROMLeft",
        "advPassiveHipROMRight",
        "ankleROMPlantarLeft",
        "ankleROMPlantarRight",
        "ankleROMDorsalLeft",
        "ankleROMDorsalRight",
        "advQAngle",
        "pelvicRotation",
        "legLengthDiscrepancy",
        "legLengthDiscrepancyDifference",
        "itBandLeft",
        "itBandRight",
        "hipLeft",
        "hipRight",
        "quadLeft",
        "quadRight",
        "kneeTypeLeft",
        "kneeTypeRight",
        "kneeSeverityLeft",
        "kneeSeverityRight",
        "footLeft",
        "footRight",
        "hipPositionLeft",
        "hipPositionRight",
        "torsoLeft",
        "torsoRight",
        "advActiveHipROMLeft",
        "advActiveHipROMRight",
        "bikeBrand",
        "bikeType",
        "bikeModel",
        "bikeSize",
        "bikeYear",
        "saddleBrand",
        "saddleModel",
        "saddleWidth",
        "shoeBrand",
        "shoeSize",
        "saddleHeight",
        "saddleOffset",
        "handlebarWidth",
        "stemLength",
        "stemAngle",
        "reachToHandlebar",
        "reachToGrips",
        "reachToHoods",
        "barDropFromSaddle",
        "pedalsBrand",
        "footbedLeft",
        "footbedRight",
        "crankLength",
        "finalBikeBrand",
        "finalBikeType",
        "finalBikeModel",
        "finalBikeSize",
        "finalBikeYear",
        "finalSaddleBrand",
        "finalSaddleModel",
        "finalSaddleWidth",
        "finalShoeBrand",
        "finalShoeSize",
        "finalSaddleHeight",
        "finalSaddleOffset",
        "finalHandlebarWidth",
        "finalStemLength",
        "finalStemAngle",
        "finalReachToHandlebar",
        "finalReachToGrips",
        "finalReachToHoods",
        "finalBarDropFromSaddle",
        "finalPedalsBrand",
        "finalFootbedLeft",
        "finalFootbedRight",
        "finalCrankLength",
        "forefootWedgeLeft",
        "forefootWedgeRight",
        "cleatWedgeLeft",
        "cleatWedgeRight",
        "cleatRotationLeft",
        "cleatRotationRight",
        "cleatLateralLeft",
        "cleatLateralRight",
        "cleatForAftPlacementLeft",
        "cleatForAftPlacementRight",
        "cleatLiftLeft",
        "cleatLiftRight",
    )

    val HEADERS: List<String> = META_HEADERS + FORM_HEADERS + listOf("json_form_error")

    init {
        val sample = formValues(InputForm())
        require(FORM_HEADERS.size == sample.size) {
            "FORM_HEADERS.size=${FORM_HEADERS.size} formValues.size=${sample.size}"
        }
    }

    fun rowValues(
        dao: BikeFittingDAO,
        form: InputForm?,
        jsonFormError: String?,
    ): List<String?> {
        return rowValues(
            CsvRowMeta(
                id = dao.id,
                fullName = dao.fullName,
                fitterFullName = dao.fitterFullName,
                sessionInstant = dao.date,
                submissionDate = dao.submissionDate,
                hasPdf = dao.pdfFile != null,
            ),
            form,
            jsonFormError,
        )
    }

    fun rowValues(
        meta: CsvRowMeta,
        form: InputForm?,
        jsonFormError: String?,
    ): List<String?> {
        val metaCells = listOf(
            meta.id,
            meta.fullName,
            meta.fitterFullName,
            meta.sessionInstant.toString(),
            meta.submissionDate.toString(),
            if (meta.hasPdf) "true" else "false",
        )
        val formCells = if (form != null) formValues(form) else List(FORM_HEADERS.size) { null }
        return metaCells + formCells + listOf(jsonFormError)
    }

    private fun formValues(form: InputForm): List<String?> {
        val f = form.fitter
        return listOf(
            cell(form.date),
            cell(form.fullName),
            cell(form.email),
            cell(form.phone),
            cell(f?.fullName),
            cell(f?.email),
            cell(f?.phone),
            cell(form.cyclingExperienceLevel),
            cell(form.cyclingExperienceYears),
            cell(form.cyclingFrequency),
            cell(form.cyclingProblem),
            cell(form.cyclingConcerns),
            cell(form.ischialTuberosity),
            cell(form.height),
            cell(form.inseam),
            cell(form.shoulderWidth),
            cell(form.footLengthLeft),
            cell(form.footLengthRight),
            cell(form.footWidthLeft),
            cell(form.footWidthRight),
            cell(form.forefootAngulationTypeLeft),
            cell(form.forefootAngulationTypeRight),
            cell(form.forefootAngulationSeverityLeft),
            cell(form.forefootAngulationSeverityRight),
            cell(form.rearFootStructureLeft),
            cell(form.rearFootStructureRight),
            cell(form.neutralArchHeightLeft),
            cell(form.neutralArchHeightRight),
            cell(form.lowerExtremityAlignmentLeft),
            cell(form.lowerExtremityAlignmentRight),
            cell(form.advLowerExtremityAlignment),
            cell(form.levelPelvis),
            cell(form.spinalCurveEvaluation),
            cell(form.advScapularPositionType),
            cell(form.advScapularPositionSeverity),
            cell(form.cervicalSpineROM),
            cell(form.shoulderROM),
            cell(form.hamstringROMLeft),
            cell(form.hamstringROMRight),
            cell(form.hipROMLeft),
            cell(form.hipROMRight),
            cell(form.advPassiveHipROMLeft),
            cell(form.advPassiveHipROMRight),
            cell(form.ankleROMPlantarLeft),
            cell(form.ankleROMPlantarRight),
            cell(form.ankleROMDorsalLeft),
            cell(form.ankleROMDorsalRight),
            cell(form.advQAngle),
            cell(form.pelvicRotation),
            cell(form.legLengthDiscrepancy),
            cell(form.legLengthDiscrepancyDifference),
            cell(form.itBandLeft),
            cell(form.itBandRight),
            cell(form.hipLeft),
            cell(form.hipRight),
            cell(form.quadLeft),
            cell(form.quadRight),
            cell(form.kneeTypeLeft),
            cell(form.kneeTypeRight),
            cell(form.kneeSeverityLeft),
            cell(form.kneeSeverityRight),
            cell(form.footLeft),
            cell(form.footRight),
            cell(form.hipPositionLeft),
            cell(form.hipPositionRight),
            cell(form.torsoLeft),
            cell(form.torsoRight),
            cell(form.advActiveHipROMLeft),
            cell(form.advActiveHipROMRight),
            cell(form.bikeBrand),
            cell(form.bikeType),
            cell(form.bikeModel),
            cell(form.bikeSize),
            cell(form.bikeYear),
            cell(form.saddleBrand),
            cell(form.saddleModel),
            cell(form.saddleWidth),
            cell(form.shoeBrand),
            cell(form.shoeSize),
            cell(form.saddleHeight),
            cell(form.saddleOffset),
            cell(form.handlebarWidth),
            cell(form.stemLength),
            cell(form.stemAngle),
            cell(form.reachToHandlebar),
            cell(form.reachToGrips),
            cell(form.reachToHoods),
            cell(form.barDropFromSaddle),
            cell(form.pedalsBrand),
            cell(form.footbedLeft),
            cell(form.footbedRight),
            cell(form.crankLength),
            cell(form.finalBikeBrand),
            cell(form.finalBikeType),
            cell(form.finalBikeModel),
            cell(form.finalBikeSize),
            cell(form.finalBikeYear),
            cell(form.finalSaddleBrand),
            cell(form.finalSaddleModel),
            cell(form.finalSaddleWidth),
            cell(form.finalShoeBrand),
            cell(form.finalShoeSize),
            cell(form.finalSaddleHeight),
            cell(form.finalSaddleOffset),
            cell(form.finalHandlebarWidth),
            cell(form.finalStemLength),
            cell(form.finalStemAngle),
            cell(form.finalReachToHandlebar),
            cell(form.finalReachToGrips),
            cell(form.finalReachToHoods),
            cell(form.finalBarDropFromSaddle),
            cell(form.finalPedalsBrand),
            cell(form.finalFootbedLeft),
            cell(form.finalFootbedRight),
            cell(form.finalCrankLength),
            cell(form.forefootWedgeLeft),
            cell(form.forefootWedgeRight),
            cell(form.cleatWedgeLeft),
            cell(form.cleatWedgeRight),
            cell(form.cleatRotationLeft),
            cell(form.cleatRotationRight),
            cell(form.cleatLateralLeft),
            cell(form.cleatLateralRight),
            cell(form.cleatForAftPlacementLeft),
            cell(form.cleatForAftPlacementRight),
            cell(form.cleatLiftLeft),
            cell(form.cleatLiftRight),
        )
    }

    private fun cell(value: Any?): String? {
        if (value == null) return null
        return when (value) {
            is Double -> String.format(Locale.US, "%s", value)
            else -> value.toString()
        }
    }
}
